language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anjith/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true anjith/react-test npm test

after_success:
  - docker build -t anjith/multi-client ./client
  - docker build -t anjith/multi-nginx ./nginx
  - docker build -t anjith/multi-server ./server
  - docker build -t anjith/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push anjith/multi-client
  - docker push anjith/multi-nginx
  - docker push anjith/multi-server
  - docker push anjith/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-471045315326
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
